### ISSUE TITLE
Combine servers slot aren't working.

### ISSUE THREAD

**Issue by DummyU8** [Viperize/QueryFacade-PocketMine#1]
I pretty sure I configured it correctly, I tryna combine all my networks slot but in the console, it keeps showing me error about asynctask and it does nothing.

**Comment by ifvictr** [comment]
@DummyU8 Not enough information provided. Please tell me the message you received on the console.

**Comment by DummyU8** [comment]
`Fatal error: Uncaught RuntimeException: Threaded members previously set to Threaded objects are immutable, cannot overwrite result in phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/scheduler/AsyncTask.php:61
Stack trace:
#0 [internal function]: pocketmine\scheduler\AsyncTask->run()
#1 {main}
  thrown in phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/scheduler/AsyncTask.php on line 61
[14:59:38] [Server thread/CRITICAL]: Could not execute asynchronous task QueryServerTask: Task crashed`
I currently using latest Genisys version.

**Comment by ifvictr** [comment]
@DummyU8 This doesn't appear to be QueryFacade's problem, the fault is in Genisys. Please note that QueryFacade was meant to be run on [PocketMine-MP](https://github.com/PocketMine/PocketMine-MP), not any derivatives of it. And also, this might be an new bug, please report this issue to [Genisys](https://github.com/iTXTech/Genisys), and see what they do about it.
